language: java
jdk:
  - oraclejdk8
sudo: required
services:
  - docker


cache:
  directories:
    - $HOME/.m2/repository/

deploy:
  - provider: script
    script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn docker:build -DpushImage"
    skip_cleanup: true
    on:
      branch: master
