language: java
jdk:
  - oraclejdk8
sudo: required
services:
  - docker

cache:
  directories:
    - $HOME/.m2/repository/

deploy:
  provider: script
  script: "mvn -s .travis.settings.xml -DpushImage docker:build"
  skip_cleanup: true
  on:
    branch: master
  
notifications:
  slack: idugalic:1roOPmlQdmPIn37c3jqgmAq8
