language: java
jdk:
  - oraclejdk8
sudo: required
services:
  - docker

deploy:
  provider: script
  script: "mvn -s .travis.settings.xml -DpushImage docker:build"
  skip_cleanup: true
  on:
    branch: master

notifications:
  slack: namics-bg:IkiLLktP3IopKi5huEwiuk0z
