spring:
  application:
    name: reactive-company-service

server:
  port: ${PORT:8080}

eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.registry.credentials.uri:http://localhost:8761}/eureka/

---
spring:
  profiles: docker
  data:
    mongodb:
      uri: mongodb://mongodb:27017/reactivecompany

eureka:
# Register our service to Eureka using hostnames in a Docker environment will not work, they will all get
# one and the same hostname. Instead we configure them to use its IP address during registration with Eureka.
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/
